In [ ]:
import pandas as pd

# The MetObjects dataset is too large for GitHub so we will only use MetObjects_FINAL, but this is the code to create MetObjects_FINAL
df = pd.read_csv('MetObjects.csv')
df

/var/folders/m4/75clkt4j5jx9w_h8f1z5tb0c0000gn/T/ipykernel_51322/3993935901.py:3: DtypeWarning: Columns (5,7,10,11,12,13,14,34,35,36,37,38,39,40,41,42,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../DATA/MetObjects.csv')

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484951,55.621.134,False,False,False,900605,NaN,Drawings and Prints,1955,Print,Holiday Card,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
484952,1977.646,False,False,False,900606,NaN,Drawings and Prints,1977,Print,Brooklyn Local,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
484953,33.40.1,False,False,False,900633,NaN,Drawings and Prints,1933,Print,Yesterday and Today,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
484954,170.1 C42,True,False,False,900717,NaN,The Libraries,NaN,NaN,"De la loi du contraste simultané des couleurs,...",...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
484955,17.3.3457,False,False,False,900748,NaN,Drawings and Prints,1917,Print,Madison Square - Fifth Avenue and Broadway at ...,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

In [4]:
# Drop all columns except 'Object Number', 'Title', 'Period', and 'Link Resource'
drop_columns = []
for col in df:
    if col != 'Object Number' and col != 'Title' and col != 'Period' and col != 'Link Resource':
        drop_columns.append(col)
df_small = df.drop(drop_columns, axis='columns')
df_small

,Object Number,Title,Period,Link Resource
0,1979.486.1,One-dollar Liberty Head Coin,NaN,http://www.metmuseum.org/art/collection/search/1
1,1980.264.5,Ten-dollar Liberty Head Coin,NaN,http://www.metmuseum.org/art/collection/search/2
2,67.265.9,Two-and-a-Half Dollar Coin,NaN,http://www.metmuseum.org/art/collection/search/3
3,67.265.10,Two-and-a-Half Dollar Coin,NaN,http://www.metmuseum.org/art/collection/search/4
4,67.265.11,Two-and-a-Half Dollar Coin,NaN,http://www.metmuseum.org/art/collection/search/5
...,...,...,...,...
484951,55.621.134,Holiday Card,NaN,http://www.metmuseum.org/art/collection/search...
484952,1977.646,Brooklyn Local,NaN,http://www.metmuseum.org/art/collection/search...
484953,33.40.1,Yesterday and Today,NaN,http://www.metmuseum.org/art/collection/search...
484954,170.1 C42,"De la loi du contraste simultané des couleurs,...",NaN,http://www.metmuseum.org/art/collection/search...
484955,17.3.3457,Madison Square - Fifth Avenue and Broadway at ...,NaN,http://www.metmuseum.org/art/collection/search...

In [ ]:
# Print Unique values in Period column
df_small = df_small[df_small['Period'].notna()]
print(len(df_small))
df_small['Period'].unique()
df_small['Period'].value_counts()

91143

Period
Edo period (1615–1868)                                         9127
Archaic                                                        7719
New Kingdom                                                    6965
Classical                                                      6954
Middle Kingdom                                                 4668
                                                               ...
period of Chinese Han occupation                                  1
Angkor period, Khmer style of Bakong                              1
Edo (1615–1868) or Meiji (1868–1912)                              1
Qing dynasty, Yongzheng (1723–35)–Qianlong (1736–95) period       1
Southern Song (1127–1279) to Yuan dynasty (1271–1368)             1
Name: count, Length: 1891, dtype: int64

In [6]:
# Display value counts as DataFrame with better formatting
period_counts = df_small['Period'].value_counts().to_frame()
period_counts.columns = ['Count']
print(f"Total unique periods: {len(period_counts)}")
print("\nTop 10 most common periods:")
print(period_counts.head(10))

Total unique periods: 1891

Top 10 most common periods:
                                             Count
Period
Edo period (1615–1868)                        9127
Archaic                                       7719
New Kingdom                                   6965
Classical                                     6954
Middle Kingdom                                4668
Qing dynasty (1644–1911)                      4437
New Kingdom, Ramesside                        3745
Archaic/Classical                             1967
Third Intermediate Period                     1343
Edo (1615–1868) or Meiji period (1868–1912)   1249

In [17]:
df_small.to_csv('MetObjects_FINAL.csv', index=False)